name: "Deploy branch to test"

on:
  workflow_call:

jobs:
  create-test-branch:
    name: "Create new test branch"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      #       - name: Delete branche
      #         run: echo git branch -D test/${{ steps.extract_branch.outputs.branch }}-${{ github.actor }} &>/dev/null

      - name: Checkout to branch
        run: git checkout ${{ github.event.ref }}

      - name: Create test branch
        run: git checkout -b test/${{ steps.extract_branch.outputs.branch }}-${{ github.actor }}-$(date +%s)

      - name: Push new branch
        run: git push origin test/${{ steps.extract_branch.outputs.branch }}-${{ github.actor }}-$(date +%s)
