name: Create draft pull request

on:
  workflow_call:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create feature pr
        uses: thomaseizinger/create-pull-request@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          head: ${{ github.event.ref }}
          base: develop
          title: Merge ${{ github.event.ref }} into develop branch by @${{ github.actor }}
          draft: true
          body: |
            🔗 **Issue Link:** [Link to the associated issue or ticket]
            
            ** 📝 Description:**
            [Provide a brief description of the changes introduced by this pull request.]
            
            ## 👀 Testing Instructions
            
            Please follow these steps to test the changes:
            
            1. [List the testing steps, e.g., "Clone the repository."]
            2. [List any commands to run or settings to configure, e.g., "Run 'npm install'."]
            3. [Provide expected outcomes or results, e.g., "The application should start without errors."]
            
            ## 🤓 Commit/branch Guidelines
            
            - [Use clear and descriptive commit messages.]
            - [Reference the related issue by naming the branch with a link to ticket (e.g., `git checkout -b "feature/CU-861n9uq1u-Navigation-Menu`).]
            - [Separate commits for logical changes or features.]
            - [Ensure each commit is self-contained and functional.
