name: Generate documentation.

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - release/*
    paths:
      - 'wiki/**.md'
      - 'wiki/images/**'

jobs:
  check:
    uses: bravoure/action-templates/.github/workflows/generate-documentation.yml@main
