name: Build, Run, Test, Lint and Succeed.

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  check:
    uses: bravoure/action-templates/.github/workflows/v2/pull-request-check.yml@main
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
