name: Ready for Review
on:
  pull_request:
    branches:
      - develop
    types:
      - ready_for_review

jobs:
  add_label:
    uses: bravoure/action-templates/.github/workflows/ready-for-review.yml@main
