name: Sync assets manual

on:
  workflow_dispatch:

jobs:
  add_label:
    uses: bravoure/action-templates/.github/workflows/sync-assets.yml@v2
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
