name: "Generate documentation"

on:
  workflow_call:

env:
  USER_NAME: bravoure-team
  USER_EMAIL: login@bravoure.nl
  OWNER: ${{ github.event.repository.owner.name }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}xw

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: wiki
          images_dir: images
          table_of_contents: true
          output_dir: documentation/
          build_html: false
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated pdf version of the docs
      - name: Checkout wiki code
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: tmp_wiki
      - name: Push to wiki
        run: |
          rsync -av --delete wiki/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "Add changes" && git push
