name: Build, Run, Test, Lint and Succeed.

on:
  workflow_call:
    secrets:
      GH_PAT:
        required: true

env:
  CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress

jobs:
  checks:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3.5.0
        with:
          node-version-file: "frontend/.nvmrc"
          cache: "npm"

      - name: Installing dependencies 📦
        run: cd frontend && npm ci

      - name: Running linter 🔍
        run: |
          [ -f /frontend/tsconfig.json ] && cd frontend && npm run ts-lint-pr
          cd frontend && npm run lint-pr

  build:
    name: Build & test
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - uses: actions/checkout@v3

      - name: "Validate composer.json and composer.lock"
        working-directory: backend
        run: "composer validate --strict --no-check-version"

      - name: "Determine composer cache directory"
        working-directory: backend
        id: "determine-composer-cache-directory"
        run: echo "directory=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.determine-composer-cache-directory.outputs.directory }}"
          key: "php-composer-${{ hashFiles('backend/composer.lock') }}"
          restore-keys: "php-composer-"

      - name: Composer install
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cp backend/.env.actions.example backend/.env
          cp frontend/.env.local.actions frontend/.env.local
          printf "%s\n" "<?php" "	return [" "'allowAdminChanges' => false" "];" >backend/config/local_config.php
          chmod 666 backend/.env
          composer config --global github-oauth.github.com $GITHUB_TOKEN
          docker compose -f docker-compose.ghactions.yml up -d database
          cd backend
          composer clear-cache
          rm -rf vendor
          composer install

      - name: Craft install
        run: |
          chmod -R 777 backend/storage
          chmod -R 777 backend/web
          chmod 666 backend/.env
          docker compose -f docker-compose.ghactions.yml run --rm queue php craft install/craft --email login@bravoure.nl --password bravoure --interactive=0
          docker compose -f docker-compose.ghactions.yml run --rm queue php craft project-seeder-module/seeder/seed-db
          docker compose -f docker-compose.ghactions.yml run --rm queue php craft resave/entries

      - name: Start environment
        run: |
          docker compose -f docker-compose.ghactions.yml up -d webserver queue redis backend database

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat frontend/.nvmrc)"
        id: nvm

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v3.5.0
        with:
          node-version-file: "frontend/.nvmrc"
          cache: "npm"

      - name: Frontend build
        working-directory: frontend
        run: |
          npm ci
          npm run build && (npm run start&)

      - name: Install Cypress and run tests
        uses: cypress-io/github-action@v4.2.0
        with:
          working-directory: e2e
          browser: chrome

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: e2e/cypress/videos
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: craft-logs
          path: backend/storage/logs
          retention-days: 30

      - name: Webserver logs
        if: always()
        run: |
          if docker compose -f docker-compose.ghactions.yml ps | grep webserver; then
            docker compose -f docker-compose.ghactions.yml logs webserver
          else
            echo "docker container webserver is not running, skipping webserver logs."
          fi