name: Sync assets
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_S3_BUCKET:
        required: true

jobs:
  sync-assets:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets. AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync images to accept
        run:
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/images s3://${{ secrets.AWS_S3_BUCKET }}/images_accept
      - name: Sync images to local
        run:
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/images s3://${{ secrets.AWS_S3_BUCKET }}/images_local
      - name: Sync videos to accept
        run:
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/videos s3://${{ secrets.AWS_S3_BUCKET }}/videos_accept
      - name: Sync videos to local
        run:
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/videos s3://${{ secrets.AWS_S3_BUCKET }}/videos_local
      - name: Sync downloads to accept
        run:
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/downloads s3://${{ secrets.AWS_S3_BUCKET }}/downloads_accept
      - name: Sync downloads to local
        run:
          aws s3 sync s3://${{ secrets.AWS_S3_BUCKET }}/downloads s3://${{ secrets.AWS_S3_BUCKET }}/downloads_local
