name: Update PR Description

on:
  workflow_call:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Skip (deprecated workflow)
        run: |
          echo "Update PR Description workflow is deprecated."
          echo "Skipping execution."
